name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - geopandas
  - gdal
  - scikit-learn
  - ipykernel
  - seaborn
  - earthengine-api
  - geemap
  - rasterio
  - pip   # ← 追加推奨
  - pip:
      - japanize-matplotlib